# -*- mode: ruby -*-
# vi: set ft=ruby :

vagrant_root = File.dirname(__FILE__)

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.synced_folder "../../../src", "/zfs-install"

  config.vm.provider "virtualbox" do |vb|
    file_to_disk = vagrant_root + "/zfs-root.vmdk"
    unless File.exist?(file_to_disk)
      vb.customize ['createmedium', '--filename', file_to_disk, '--size', 30 * 1024, "--format", "VMDK"]
    end
    vb.customize ['storageattach', :id, '--storagectl', 'SCSI', '--port', 2, '--device', 0, '--type', 'hdd', '--medium', file_to_disk]
  end

  # config.vm.box_check_update = false
  # config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  # config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "public_network"
  # config.vm.synced_folder "../data", "/vagrant_data"

  # config.vm.provider "virtualbox" do |vb|
  #   vb.gui = true
  #   vb.memory = "1024"
  # end

  config.vm.provision "shell", inline: <<-SHELL
    /zfs-install/zfs-install.sh -l /tmp/zfs-install.log -c /tmp/zfs-install.cmd 
  SHELL
end
